name: Deploy React App to S3

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: 'Node.js version to use'
        required: true
        default: '14'
      s3_bucket_name:
        type: string
        description: 'S3 bucket name'
        required: true
      source_dir:
        type: string
        description: 'Directory of build files to deploy'
        required: true
        default: 'build'
      cloudfront_distribution_id:
        type: string
        description: 'CloudFront distribution ID for invalidation'
        required: true
      aws_region:
        type: string
        description: 'AWS region for deployment'
        required: true
        default: 'us-east-1'
      paths_to_invalidate:
        type: string
        description: 'Paths to invalidate in CloudFront'
        required: false
        default: '/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ inputs.s3_bucket_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ${{ inputs.source_dir }}
      - name: Invalidate CloudFront Distribution
        uses: chetan/invalidate-cloudfront-action@v1
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ inputs.cloudfront_distribution_id }}
          PATHS: ${{ inputs.paths_to_invalidate }}
          AWS_REGION: ${{ inputs.aws_region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
